version: '3.8'
services:
  portfolio-manan:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: portfolio
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dokploy-network" # Good practice

      # --- Routers for manansantoki.xyz (non-www) ---
      # 1. HTTP non-www: redirect to HTTPS non-www
      - "traefik.http.routers.portfolio-nonwww-http.rule=Host(`manansantoki.xyz`)"
      - "traefik.http.routers.portfolio-nonwww-http.entrypoints=web"
      - "traefik.http.routers.portfolio-nonwww-http.middlewares=redirect-scheme-https@docker" # Use a generic HTTPS redirect middleware

      # 2. HTTPS non-www: redirect to HTTPS www
      - "traefik.http.routers.portfolio-nonwww-https.rule=Host(`manansantoki.xyz`)"
      - "traefik.http.routers.portfolio-nonwww-https.entrypoints=websecure"
      - "traefik.http.routers.portfolio-nonwww-https.tls.certresolver=letsencrypt" # Important for this router to get a cert
      - "traefik.http.routers.portfolio-nonwww-https.middlewares=redirect-to-www@docker" # Your existing www redirect
      # This router does NOT define a service, as its sole purpose is to redirect.

      # --- Routers for www.manansantoki.xyz ---
      # 3. HTTP www: redirect to HTTPS www
      - "traefik.http.routers.portfolio-www-http.rule=Host(`www.manansantoki.xyz`)"
      - "traefik.http.routers.portfolio-www-http.entrypoints=web"
      - "traefik.http.routers.portfolio-www-http.middlewares=redirect-scheme-https@docker" # Use a generic HTTPS redirect middleware

      # 4. HTTPS www: serves the actual content (THIS IS YOUR WORKING ROUTER)
      - "traefik.http.routers.portfolio-www-https.rule=Host(`www.manansantoki.xyz`)"
      - "traefik.http.routers.portfolio-www-https.entrypoints=websecure"
      - "traefik.http.routers.portfolio-www-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.portfolio-www-https.service=portfolio-service@docker"

      # --- Middleware Definitions ---
      # Middleware to redirect HTTP to HTTPS
      - "traefik.http.middlewares.redirect-scheme-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-scheme-https.redirectscheme.permanent=true"

      # Middleware to redirect non-www to www (ensure it captures scheme and path)
      # This regex is more robust as it works for both http and https
      - "traefik.http.middlewares.redirect-to-www.redirectregex.regex=^https?://manansantoki\\.xyz/(.*)" # Match http OR https, escape dot
      - "traefik.http.middlewares.redirect-to-www.redirectregex.replacement=https://www.manansantoki.xyz/$${1}"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.permanent=true"

      # --- Service Definition ---
      - "traefik.http.services.portfolio-service.loadbalancer.server.port=80" # Your app's port

    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
