version: '3.8'

services:
  traefik:
    image: traefik:v2.10 # Use your preferred Traefik version
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true" # For Traefik dashboard (dev only, secure it for prod)
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=your-email@example.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080" # For Traefik dashboard (optional)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt" # Persistent storage for Let's Encrypt certificates
    networks:
      - traefik-network # Connect Traefik to the network

  portfolio-manan:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: portfolio
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio-www.rule=Host(`www.manansantoki.xyz`)"
      - "traefik.http.routers.portfolio-www.entrypoints=websecure"
      - "traefik.http.routers.portfolio-www.tls.certresolver=letsencrypt"
      - "traefik.http.routers.portfolio-www.service=portfolio-service"
      - "traefik.http.routers.portfolio-redirect.rule=Host(`manansantoki.xyz`)"
      - "traefik.http.routers.portfolio-redirect.entrypoints=websecure"
      - "traefik.http.routers.portfolio-redirect.tls.certresolver=letsencrypt"
      - "traefik.http.routers.portfolio-redirect.middlewares=redirect-to-www"
      - "traefik.http.routers.portfolio-www-http.rule=Host(`www.manansantoki.xyz`)"
      - "traefik.http.routers.portfolio-www-http.entrypoints=web"
      - "traefik.http.routers.portfolio-www-http.middlewares=redirect-to-https"
      - "traefik.http.routers.portfolio-redirect-http.rule=Host(`manansantoki.xyz`)"
      - "traefik.http.routers.portfolio-redirect-http.entrypoints=web"
      - "traefik.http.routers.portfolio-redirect-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.regex=^https://manansantoki.xyz/(.*)"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.replacement=https://www.manansantoki.xyz/$${1}"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.permanent=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.services.portfolio-service.loadbalancer.server.port=80"
    networks:
      - traefik-network # Connect portfolio to the same network

networks:
  traefik-network: {} # Docker Compose will create this network (e.g., projectname_traefik-network)
